(fix) TopicMessageQuery#unsubscribe() attempts to re-subscribe
hashgraph/hedera-sdk-js pull request #2571
Opened 2024-10-09 10:57 UTC by Jexsie

**Description**:

The `unsubscribe` method invokes the _call function, which cancels the current active subscription but doesn’t necessarily stop retry attempts, as retries are managed separately in `TopicMessageQuery`. I have added a check to prevent retries after unsubscribing in the `onError` callback

https://github.com/user-attachments/assets/6f933119-58ef-416d-8561-51d9fbd5c247

**Related issue(s)**:

Fixes #2222 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-10-09 11:00 UTC, Jexsie commented
Hope this helps

2024-10-10 17:21 UTC, Jexsie commented
Can you kindly share the snippet you run against @agadzhalov

2024-10-11 05:12 UTC, Jexsie commented
Fixed in the latest commit 

https://github.com/user-attachments/assets/3170c263-d577-4608-ae8e-6a671b78e2d9

2024-10-14 09:48 UTC, agadzhalov commented on src/topic/TopicMessageQuery.js
> +                        );
remove the console.log. We use console.logs only in our examples but not in the implementation itself. 
```suggestion
```

2024-10-14 09:48 UTC, agadzhalov requested changes
remove the console.log from TopicMessageQuery

2024-10-14 09:57 UTC, Jexsie commented
fixed

2024-10-14 10:00 UTC, agadzhalov commented
@Jexsie seems like you've forgotten to sign some of your commits because the DCO is failing.

2024-10-14 10:07 UTC, Jexsie commented
resolved @agadzhalov

2024-10-14 10:15 UTC, ivaylonikolov7 commented
You will have to sign all the commits. Otherwise when we squash the commits there might be some issues.

2024-10-14 11:54 UTC, ivaylogarnev-limechain commented
It seems like you didn't remove the console log.

2024-10-14 19:06 UTC, Jexsie commented
Sorry @Jexsie and @ivaylonikolov7, I can't really tell what happened

2024-10-15 05:24 UTC, ivaylogarnev-limechain commented
> Sorry @agadzhalov and @ivaylonikolov7, I can't tell what happened, but I have removed the console.log now

As @ivaylonikolov7 mentioned earlier, please review all of your commits (currently seven) and look into how to sign them.

2024-10-15 07:10 UTC, Jexsie commented
I have squashed all the commits into one, and signed off

2024-10-15 08:17 UTC, agadzhalov commented
@Jexsie looks like your commit is not verified, can you try to sign it off again with ammend 
```
git commit --amend --signoff
```
your commit
![image](https://github.com/user-attachments/assets/5ae27bcf-5ad9-49d4-ba82-8b467311d8af)

the resul we expect after ammend

![image](https://github.com/user-attachments/assets/93e1d3bb-e211-4dca-a832-ad898b55fd98)

2024-10-15 08:50 UTC, Jexsie commented
cant really see that verified flag. Is it okay if close this and reopen another one @agadzhalov

2024-10-15 10:09 UTC, agadzhalov commented
@Jexsie yes, it's totally ok to open a new PR, but before that have you tried with git commit ammend? If it doesn't work with ammend open a new PR

2024-10-15 10:31 UTC, closed without merging