fix: setSupplyKey
hashgraph/hedera-sdk-js pull request #828
Opened 2021-12-21 21:29 UTC by valtyr-naut

Signed-off-by: valtyr-naut <dalton.kaua@launchbadge.com>

Fixes: #805

2021-12-21 21:42 UTC, valtyr-naut commented
both setsupplyKey and setSupplyKey now exist in TokenUpdateTransaction

2021-12-22 03:26 UTC, danielakhterov requested changes

2021-12-22 03:26 UTC, danielakhterov commented on src/token/TokenUpdateTransaction.js
> -            this.setsupplyKey(props.supplyKey);
Can you deprecate `setsupplyKey`?

2021-12-22 21:29 UTC, danielakhterov approved these changes

2021-12-29 01:04 UTC, danielakhterov approved these changes

2021-12-29 01:04 UTC, merged